### ISSUE TITLE
Questions about Wayland

### ISSUE THREAD

**Issue by SSalekin** [pop-os/system76-scheduler#17]
I'm using `wayland` instead of `xorg` in my  pop 20.04, do I need to modify my `/usr/share/system76-scheduler/assignments/default.ron` like this ?

```
{
// High priority
-5: [
    "gnome-shell",
    "kwin",
    "Xorg",
    "Xwayland"     <<<===============
],
// Absolute lowest priority
19: [
    "c++",
    "cargo",
    "clang",
    "cpp",
    "g++",
    "gcc",
    "lld",
    "make",
    "rustc",
]}
```

Also, is there any reason `Wayland` is disabled from the cog wheel from pop 20.04 (need to edit `/etc/gdm3/custom.conf` file to enable), curious if it's disabled because of any regressions or conflicts with pop os.

Finally, thank you for your such great contributions to the  linux community <3

**Comment by SSalekin** [comment]
well, since no one is posting an answer for 3 months, I'll just close it. Ty,

**Comment by jacobgkau** [comment]
> Also, is there any reason `Wayland` is disabled from the cog wheel from pop 20.04 (need to edit `/etc/gdm3/custom.conf` file to enable), curious if it's disabled because of any regressions or conflicts with pop os.

Wayland is disabled by default in Pop!_OS because it does not have feature parity and hardware stability on all System76 hardware. It will be enabled when it has those things.

Wayland being enabled or disabled by default in Pop!_OS does not have anything to do with the sytem76-scheduler component.

> I'm using `wayland` instead of `xorg` in my pop 20.04, do I need to modify my `/usr/share/system76-scheduler/assignments/default.ron` like this ?

Off the top of my head, gnome-shell would be a Wayland compositor (see [this answer from a web search](https://unix.stackexchange.com/questions/599335/is-wayland-display-server-a-userspace-process)), so the `gnome-shell` process will cover for Wayland what the `Xorg` process does for X11. The only other related process would be `Xwayland` for running X11 apps on Wayland, which is already in the list. So no, there would not be anything to optionally add (you can already tell you don't "need" to add anything if your system is working.)

If you do make changes to the config, you should do so in `/etc`, not `/usr/share`, since `/usr/share` gets overwritten on package updates.

**Comment by jacobgkau** [comment]
I just noticed you are asking about adding `Xwayland` to your list and it's not part of the default list. I don't see any reason why you wouldn't want to do that, it will only benefit legacy X11 apps and not any apps running as Wayland clients. You can check the output of a program such as `top` to see if `Xwayland` is getting a lot of CPU usage, if it is, then adding it to the high-priority list may speed up the drawing of those apps somewhat.
