### ISSUE TITLE
Missing INSTALL.md file for instalk instructions

### ISSUE THREAD

**Issue by iadegesso** [pop-os/system76-scheduler#68]
Hi,
to build and install on mey Gentoo, I did the followng;

1. git clone https://github.com/pop-os/system76-scheduler.git
2. cd system76-scheduler
3. EXECSNOOP_PATH="/usr/sbin/execsnoop-bpfcc" cargo build --release
4. cd target/release
5. cp system76-scheduler /usr/bin/

It seem to work, but I will appeciate if you could add official install instructions.

Iade

**Comment by mmstick** [comment]
See the [debian/rules file](https://github.com/pop-os/system76-scheduler/blob/master/debian/rules) for an example. All pop-os projects that build packages will have them. You can use `just -l` to list options for the justfile.

If you don't require vendoring, and just want to build locally rather than package it.

```
just execsnoop="/usr/sbin/execsnoop-bpfcc"
sudo just sysconfdir="/usr/share" install
```

**Comment by mbana** [comment]
If you feel that this PR, https://github.com/pop-os/system76-scheduler/pull/75, is fine, then do please mark this issue as resolved.
